name: Publish to TestPyPI

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: '3.12'
    - name: Install uv
      run: pip install uv
    - name: Build distributions
      run: uv build
    - name: Upload build artifacts
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist/

  publish-testpypi:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/django-unified-signals

    permissions:
      id-token: write

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@master
      with:
        name: dist
        path: dist/
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
