name: Release

on:
  workflow_dispatch:

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    concurrency:
      group: release
      cancel-in-progress: false

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Semantic Version Release
      uses: python-semantic-release/python-semantic-release@v10.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        git_committer_name: "github-actions[bot]"
        git_committer_email: "github-actions[bot]@users.noreply.github.com"
